#!/bin/bash

release_file=/etc/os-release

if grep -q "Arch" $release_file || grep -q "Linux" $release_file || grep -q "Pop" $release_file || grep -q "Ubuntu" $release_file
then
	sudo apt upgrade && sudo apt dist-upgrade
fi
